### ISSUE TITLE
(RuntimeError) unexpected case: 3 ongoing rules for rule "Palestine" (2023c)

### ISSUE THREAD

**Issue by OldhamMade** [mathieuprog/tz#18]
```
10:18:11.182 [info]  Tz is downloading the latest IANA time zone database (version 2023c)...

10:18:12.298 [info]  Tz download done

10:18:12.348 [info]  Tz is recompiling time zone periods...
** (RuntimeError) unexpected case: 3 ongoing rules for rule "Palestine"
    (tz 0.20.1) lib/compiler.ex:27: anonymous fn/1 in Tz.Compiler.compile/0
    (elixir 1.13.4) lib/enum.ex:942: anonymous fn/3 in Enum.each/2
    (stdlib 4.3) maps.erl:411: :maps.fold_1/3
    (elixir 1.13.4) lib/enum.ex:2408: Enum.each/2
    (tz 0.20.1) lib/compiler.ex:24: anonymous fn/3 in Tz.Compiler.compile/0
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (tz 0.20.1) lib/compiler.ex:20: Tz.Compiler.compile/0
    (tz 0.20.1) lib/updater.ex:20: Tz.Updater.maybe_recompile/0
```

**Comment by mathieuprog** [comment]
Do you have latest version?

**Comment by OldhamMade** [comment]
> Do you have latest version?

Sorry, no, I was somehow using a very old version. Apologies for the spam!

**Comment by mathieuprog** [comment]
Np this had been recently fixed where Palestine updates led to a new edge case in the code that had to be addressed.
