### ISSUE TITLE
GenServer :tzdata_release_updater terminating * 2nd argument: not a tuple

### ISSUE THREAD

**Issue by rlopzc** [mathieuprog/tz#30]
Error:
```
2024-09-06T18:32:30.819Z
	
18:32:30.813 [error] GenServer :tzdata_release_updater terminating
	
main
2024-09-06T18:32:30.819Z
	
** (ArgumentError) errors were found at the given arguments:
	
main
2024-09-06T18:32:30.819Z
	
* 2nd argument: not a tuple
	
main
2024-09-06T18:32:30.819Z
	
:erlang.element(1, :error)
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
	
main
2024-09-06T18:32:30.819Z
	
(tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
	
main
2024-09-06T18:32:30.819Z
	
Last message: :check_if_time_to_update
	
main
2024-09-06T18:32:30.819Z
	
State: []
	
main
2024-09-06T18:32:30.430Z
	
18:32:30.430 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 05 Sep 2024 18:47:42 GMT.
	
main
```

**Comment by mathieuprog** [comment]
This is an issue on the tzdata library, not tz.

You may switch to tz.
